
server:
  port: 8888

spring:
  datasource:     #配置数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///users
    username: root
    password: root
  thymeleaf:      #配置thymeleaf模板
    servlet:
      content-type: text/html
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
  redis:          #配置redis
    database: 1
    host: 124.222.91.53
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 8 #最大连接
        max-wait: 100 #连接等待时间
        min-idle: 0 #最小空闲连接
        max-idle: 8 #最大空闲连接

mybatis:          #mybatis配置
  type-aliases-package: com.example.springredis.domain
  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
