
# false表示开发，true表示生产
jpush:
  environment: true
  appKey: 604bad08c925629ad19c0b2d
  masterSecret: da7648422f5aa5e45e3cbaaf

xxl:
  job:
    accessToken: xxxxxxxxxxx
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      address: ''
      appname: ${spring.application.name}
      ip: 127.0.0.1
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 7
      port: 10610